### ISSUE TITLE
Fix 1 frame infodisplay delay

### ISSUE THREAD

**Issue by kierio04** [TASLabz/dolphin#118]
Current fix is to disable immediately present XFB, however this causes TASLabz/dolphin#117 as a result. Closing this issue should require a solution which also closes TASLabz/dolphin#117.

**Comment by kierio04** [comment]
Note: Duplicate of #115 with more context on the situation we're in and the dependency on the paired issue.

**Comment by ximk** [comment]
I'm going to close this and just put the comment in quotes in #115. No point in opening an issue to explain an issue.
