### ISSUE TITLE
In-game frame counts don't update correctly

### ISSUE THREAD

**Issue by ximk** [TASLabz/dolphin#12]
Currently, Python scripts have the possibility of desyncing/freezing for a frame, which is especially noticeable with scripts that require frame perfect inputs. Games played without these scripts are able to sync with other Dolphin versions, so it is believed to be an issue to the way Python and Dolphin communicate. The reason behind these desyncs appears to be related to the frame count stopping at random intervals for a frame and resuming updates the frame after, or something related to how `set_gc_buttons` processes inputs.

**Comment by ximk** [comment]
The desync can be fixed through the python code itself (hint: don't use `while True` loops), but the "freezing/frame repeating" issue still occurs. There are currently no leads as to why this happens.

**Comment by ximk** [comment]
Changed issue title to better reflect the current problem being faced.

**Comment by vabold** [comment]
Can't repro.

**Comment by ximk** [comment]
> Can't repro.

Communication issue, this still occurs.

**Comment by vabold** [comment]
Please provide repro steps.

**Comment by ximk** [comment]
There is not any surefire way to reproduce this in the exact same way every time, but using scripts that require lots of precise player inputs in order (like playback scripts) will eventually desync around a minute in without a hack.

Specific Example:
1. Obtain a TASToolKit CSV file
2. Remove lines 14 and 15 (the hack) in `pianoroll_player.py` (located in TASLabz/mkw-scripts):
3. Load `pianoroll_player` on the same track that the TASToolKit file was saved on, and match the character and vehicle that was used.
4. The desync will occur usually within a minute or so.

**Comment by vabold** [comment]
Tentatively considered solved in dc707168af555fea1b534e64550ebc56c7c62174. Any future desyncs should be reported here. I will keep the issue open until June 1.

**Comment by ximk** [comment]
No issues have been found since https://github.com/TASLabz/dolphin/commit/dc707168af555fea1b534e64550ebc56c7c62174, closing until further notice.
