### ISSUE TITLE
Port stable 5.0's TAS Input window to Qt

### ISSUE THREAD

**Issue by vabold** [TASLabz/dolphin#24]

**Comment by malleoz** [comment]
I might be arguing semantics but I wouldn't really call this a port... It's an entirely different UI framework, so there isn't a quick easy way to do this. Nonetheless this is what I will try to work on now

**Comment by vabold** [comment]
I referred to it as a port because it's between frameworks - if it wasn't, I would probably use the term "revert".

**Comment by ximk** [comment]
Resolved in #25.
