### ISSUE TITLE
TAS Input responsiveness during frame advance is reliant on game framerate

### ISSUE THREAD

**Issue by malleoz** [TASLabz/dolphin#32]
Steps to reproduce:
1. Set game speed limit to 50%
2. Open TAS Input
3. With TAS Input as window-of-focus, hold down frame advance hotkey
4. With hotkey held down, hold down left-click and circle around the Main Stick
5. Notice latency and delay in both TAS Input window AND the input display
6. Let go of frame advance hotkey
7. Notice TAS Input Window snaps back to full responsiveness.

This is a problem even in upstream Dolphin 5.0-19159. This may be a very tough issue to fix. According to @Gaberboo frame advance is also problematic at speeds exceeding 100%.

**Comment by malleoz** [comment]
This is not fully resolved with that commit.

**Comment by malleoz** [comment]
This was as a result of the memory view widget (the debug panel one) acquiring the CPU lock (twice?) every frame, even when the widget is not enabled. This incredibly taxing operation would end up stalling the CPU thread enough for latency issues to be introduced for TAS Input window.

This is addressed and fixed in https://github.com/TASLabz/dolphin/pull/38

Good to close this issue after merge.

**Comment by ximk** [comment]
Resolved in 330360a774d55ca838a39523267dab8bf70d672f outside of use with the debugging UI, which is a non-issue at the moment.
