### ISSUE TITLE
Create a function that returns the Game ID in the `utils` module

### ISSUE THREAD

**Issue by ximk** [TASLabz/dolphin#51]

**Comment by vabold** [comment]
Perhaps better suited for the `core` module.

**Comment by ximk** [comment]
Either the `memory` or `utils` module is fine with me, I just think it fits better in the `memory` module.

**Comment by ximk** [comment]
> Perhaps better suited for the `core` module.

*Referring to what is currently known as `utils`, but that may change in the future.

**Comment by ximk** [comment]
> > Perhaps better suited for the `core` module.
> 
> *Referring to what is currently known as `utils`, but that may change in the future.

The name is not changing, updating the title now.

**Comment by ximk** [comment]
Resolved in https://github.com/TASLabz/dolphin/commit/6cdd373378844504952d230c8f2293c5885b6f24.
