### ISSUE TITLE
Compiler errors at Source/Core/Core/Config/MainSettings.h

### ISSUE THREAD

**Issue by saltq144** [TASLabz/dolphin#58]
I cloned the repo (with `--recurse-submodules`), made a build folder, went to it, ran `cmake ..`, then `make -j24`.

Errors:

`
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:248:14: error: ‘Info’ does not name a type
  248 | extern const Info<ShowCursor> MAIN_SHOW_CURSOR;
` (repeated lots)
and
`
In file included from /usr/include/X11/Xlib.h:44,
                 from /usr/include/X11/extensions/Xrender.h:28,
                 from /usr/include/X11/extensions/Xrandr.h:33,
                 from /home/saltq/dev/pycore-dolphin/Source/Core/UICommon/X11Utils.h:10,
                 from /home/saltq/dev/pycore-dolphin/Source/Core/UICommon/X11Utils.cpp:4:
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:235:3: error: expected identifier before numeric constant
  235 |   None,
      |   ^~~~
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:235:3: error: expected ‘}’ before numeric constant
In file included from /home/saltq/dev/pycore-dolphin/Source/Core/UICommon/X11Utils.cpp:19:
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:234:1: note: to match this ‘{’
  234 | {
      | ^
In file included from /usr/include/X11/Xlib.h:44,
                 from /usr/include/X11/extensions/Xrender.h:28,
                 from /usr/include/X11/extensions/Xrandr.h:33,
                 from /home/saltq/dev/pycore-dolphin/Source/Core/UICommon/X11Utils.h:10,
                 from /home/saltq/dev/pycore-dolphin/Source/Core/UICommon/X11Utils.cpp:4:
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:235:3: error: expected unqualified-id before numeric constant
  235 |   None,
      |   ^~~~
In file included from /home/saltq/dev/pycore-dolphin/Source/Core/UICommon/X11Utils.cpp:19:
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:240:19: error: ‘OutlineRes’ was not declared in this scope; did you mean ‘Config::OutlineRes’?
  240 | extern const Info<OutlineRes> MAIN_IMGUI_OUTLINE_RES;
      |                   ^~~~~~~~~~
      |                   Config::OutlineRes
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:233:12: note: ‘Config::OutlineRes’ declared here
  233 | enum class OutlineRes
      |            ^~~~~~~~~~
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:240:19: error: ‘OutlineRes’ was not declared in this scope; did you mean ‘Config::OutlineRes’?
  240 | extern const Info<OutlineRes> MAIN_IMGUI_OUTLINE_RES;
      |                   ^~~~~~~~~~
      |                   Config::OutlineRes
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:233:12: note: ‘Config::OutlineRes’ declared here
  233 | enum class OutlineRes
      |            ^~~~~~~~~~
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:240:19: error: ‘OutlineRes’ was not declared in this scope; did you mean ‘Config::OutlineRes’?
  240 | extern const Info<OutlineRes> MAIN_IMGUI_OUTLINE_RES;
      |                   ^~~~~~~~~~
      |                   Config::OutlineRes
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:233:12: note: ‘Config::OutlineRes’ declared here
  233 | enum class OutlineRes
      |            ^~~~~~~~~~
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:240:19: error: ‘OutlineRes’ was not declared in this scope; did you mean ‘Config::OutlineRes’?
  240 | extern const Info<OutlineRes> MAIN_IMGUI_OUTLINE_RES;
      |                   ^~~~~~~~~~
      |                   Config::OutlineRes
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:233:12: note: ‘Config::OutlineRes’ declared here
  233 | enum class OutlineRes
      |            ^~~~~~~~~~
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:240:19: error: ‘OutlineRes’ was not declared in this scope; did you mean ‘Config::OutlineRes’?
  240 | extern const Info<OutlineRes> MAIN_IMGUI_OUTLINE_RES;
      |                   ^~~~~~~~~~
      |                   Config::OutlineRes
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:233:12: note: ‘Config::OutlineRes’ declared here
  233 | enum class OutlineRes
      |            ^~~~~~~~~~
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:240:19: error: ‘OutlineRes’ was not declared in this scope; did you mean ‘Config::OutlineRes’?
  240 | extern const Info<OutlineRes> MAIN_IMGUI_OUTLINE_RES;
      |                   ^~~~~~~~~~
      |                   Config::OutlineRes
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:233:12: note: ‘Config::OutlineRes’ declared here
  233 | enum class OutlineRes
      |            ^~~~~~~~~~
/home/saltq/dev/pycore-dolphin/Source/Core/Core/Config/MainSettings.h:240:14: error: ‘Info’ does not name a type
  240 | extern const Info<OutlineRes> MAIN_IMGUI_OUTLINE_RES;
      | 
`

Also warning while running `cmake`:

CMake Warning at CMakeLists.txt:684 (find_package):
  By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fmt", but
  CMake did not find one.

  Could not find a package configuration file provided by "fmt" (requested
  version 8) with any of the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed.

**Comment by malleoz** [comment]
This looks to be fixed as of #59. Closing as a result!

**Comment by saltq144** [comment]
I'd like to note that while the fix does work, it runs into another error on gcc 11.4, but not on 13.2.

Additionally regardless of compiler version, a declaration in a reasonably recent version of QT is missing.
