### ISSUE TITLE
No quick way to access Scripts widget

### ISSUE THREAD

**Issue by malleoz** [TASLabz/dolphin#68]
If you close the script widget after startup, it is not clear how to navigate back. I believe currently you have to click "Show Log", then right click the top of the log widget, and then click Script. Instead, we should have a button under View or Tools to show the Scripts list... Not sure which, argue away :)

**Comment by ximk** [comment]
Since there is a ton of blank space in the toolbar, I suggest we put the option to open the Scripts widget (among other common TASing tools like TAS Input and the log for debugging) there.

![image](https://github.com/TASLabz/dolphin/assets/104683822/d1186144-5d66-4289-8cda-3f5982160e7d)

**Comment by malleoz** [comment]
Honestly my vision is that the Log menu should only be used in drastic cases; it shouldn't be required to be immediately accessible.

I can't believe no one has suggested adding it to the toolbar before, but I do really like this idea!!!!

**Comment by ximk** [comment]
> Honestly my vision is that the Log menu should only be used in drastic cases; it shouldn't be required to be immediately accessible.

My idea was that it would be nice to have easily accessible for debugging purposes (both for script writers and script users). Perhaps the default log configuration should just be `Scripting` to simplify this?

**Comment by malleoz** [comment]
Merged https://github.com/TASLabz/dolphin/pull/69 to address the View menu problem. Keeping this open as I do think the toolbar additions are a good idea.

I guess I'm on-the-fence on whether we expect users to really use the log output. The hope is that our on-screen messages can alert anytime something goes wrong.

**Comment by ximk** [comment]
> I guess I'm on-the-fence on whether we expect users to really use the log output. The hope is that our on-screen messages can alert anytime something goes wrong.

I hope so too, but I think that since we have the space, we might as well use it. We can always remove the shortcut later if people don't get a lot of use out of it.

**Comment by ximk** [comment]
Closing issue for now because the main point of this issue was resolved, we can consider the other options at a later point.
